### ISSUE TITLE
app.gov should be removed

### ISSUE THREAD

**Issue by wslack** [18F/dns#271]
@erik-burgess - I heard from @allalala yesterday that app.gov was not renewed. What do we need to do to excise it from DNS here? Just pull the terraform file? cc @afeld

**Comment by erik-burgess** [comment]
@wslack Removing the terraform file should do it, which we should follow up with a manual review of of Route53 to ensure that it has been deleted in it's entirety. 

Following that, @fieldsey (or one of the other app.gov listed contacts) should email registrar@dotgov.gov and request cancellation of the domain so that we don't get with any unexpected renewal fees.

**Comment by wslack** [comment]
I think the domain is already cancelled? 🤷‍♂️

**Comment by afeld** [comment]
Also, less of a big deal now that dotgov.gov sits so close to us, in case we want it back 😄

**Comment by wslack** [comment]
I think we only had it as as redirect to apps.gov.
