### ISSUE TITLE
v2alt.designsystem.digital.gov should be removed

### ISSUE THREAD

**Issue by afeijoo** [18F/dns#427]
This was an alternate name set up in April 2019 when USWDS released USWDS 2. It is no longer needed.

cc: @thisisdano

**Comment by afeld** [comment]
Any idea if this was pointing to Federalist? Federalist folks: Presumably there's a cloud.gov CDN broker somewhere we need to take down.

**Comment by afeijoo** [comment]
Looping in @jeremyzilar and @thisisdano, who worked on this in 2019. See the question above from @afeld ^^^.

**Comment by amirbey** [comment]
@afeld this v2alt.designsystem.digital.gov domain is pointing to pages-redirects which is redirecting to designsystm.digital.gov.  My guess is this domain was created as a workaround to a cdn-service failure when attempting to create v2.designsystem.digital.gov  In instances when  when creating a cdn-service failed and was stuck in a loop due to some hiccup, a common workaround was to re-create a cdn-service instance with any additonal domain.  I have created https://github.com/18F/dns/pull/450 to remove this domain

**Comment by afeld** [comment]
Closed by https://github.com/18F/dns/pull/450 — @amirbey correct me if I'm wrong. Thanks all!
